### ISSUE TITLE
Sheet 17 - RTC IC identification number incorrect

### ISSUE THREAD

**Issue by simoninns** [simoninns/Acorn-Master-AIV#1]
The original Master 128 schematic only says 146818 and the chip datasheet for the MC146818P states that 1 and 16 are NC. So I'd conclude that both the new schematic and the original are incorrect, as the chip has to be a 'P' since the 'A' datasheet shows 1 and 16 to have a function.

i.e. the schematic should be marked MC146818P not MC146818A

**Comment by kgl2001** [comment]
The MC146818 and MC146818P are one of the same thing. The P suffix just defines the Plastic package case.

The MC146818A on the other hand is something subtly different. It is an upgraded version of the MC146818 which utilises pins 1 & 16 for other functions. The MC146818A also comes in various packages, including P and this is sometimes referred to as MC146818AP.

I believe your final conclusion is correct. The schematic should be marked either MC146818 or MC146818P. It should not be MC146818A.

**Comment by simoninns** [comment]
Fixed in latest commit
